image: ubuntu:16.04

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Deploy to Github Pages
        script:
          - apt-get update -y
          - apt-get install -y git
          - git push -f https://nykez:$DEPLOY_KEY@github.com/nykez/bikeshop.git HEAD