image: ubuntu:16.04

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Deploy to Github Pages
        script:
          - git push https://nykez:$DEPLOY_KEY@github.com/nykez/bikeshop.git HEAD